# Generated by Django 4.2.2 on 2023-06-28 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_std'),
    ]

    operations = [
        migrations.DeleteModel(
            name='std',
        ),
    ]
