# Generated by Django 4.2.1 on 2023-06-30 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_bck100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bck100',
        ),
    ]
