# Generated by Django 4.2.2 on 2023-07-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='emp',
        ),
    ]
